"""dependency

Revision ID: 1302e5c9144a
Revises: 
Create Date: 2026-01-16 00:49:38.927530

"""
from typing import Sequence, Union
from enum import Enum
from datetime import datetime

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column

# revision identifiers, used by Alembic.
revision: str = '1302e5c9144a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Определения прав доступа
class PermissionEnum(Enum):
    """Права доступа"""
    PROJECT_EDIT = "project:edit"
    PROJECT_DELETE = "project:delete"
    PROJECT_MANAGE_USERS = "project:manage_users"

    REQUIREMENT_CREATE = "requirement:create"
    REQUIREMENT_READ = "requirement:read"
    REQUIREMENT_UPDATE = "requirement:update"
    REQUIREMENT_DELETE = "requirement:delete"
    REQUIREMENT_APPROVE = "requirement:approve"
    REQUIREMENT_REJECT = "requirement:reject"
    REQUIREMENT_REVIEW = "requirement:review"


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('permission', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('permission')
    )
    op.create_table('roles',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('login', sa.String(length=255), nullable=False),
    sa.Column('surname', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_external_id'), 'users', ['external_id'], unique=True)
    op.create_index(op.f('ix_users_login'), 'users', ['login'], unique=True)
    op.create_table('projects',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('role_permissions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_role_permission')
    )
    op.create_index(op.f('ix_role_permissions_role_id'), 'role_permissions', ['role_id'], unique=False)
    op.create_table('requirements',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_id'], ['requirements.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_project_roles',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'project_id', name='uq_user_project')
    )
    op.create_index(op.f('ix_user_project_roles_project_id'), 'user_project_roles', ['project_id'], unique=False)
    op.create_index(op.f('ix_user_project_roles_user_id'), 'user_project_roles', ['user_id'], unique=False)
    op.create_table('req_content_histories',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('requirement_id', sa.UUID(), nullable=False),
    sa.Column('prev_content_history_id', sa.UUID(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('development_basis', sa.Text(), nullable=True),
    sa.Column('development_purpose', sa.Text(), nullable=True),
    sa.Column('description_text', sa.Text(), nullable=True),
    sa.Column('acceptance_criteria', sa.Text(), nullable=True),
    sa.Column('document_requires', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['prev_content_history_id'], ['req_content_histories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('req_workflow_histories',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('requirement_id', sa.UUID(), nullable=False),
    sa.Column('prev_workflow_history_id', sa.UUID(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['prev_workflow_history_id'], ['req_workflow_histories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('requirement_approvers',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('requirement_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('reason', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('requirement_contents',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('requirement_id', sa.UUID(), nullable=False),
    sa.Column('development_basis', sa.Text(), nullable=True),
    sa.Column('development_purpose', sa.Text(), nullable=True),
    sa.Column('description_text', sa.Text(), nullable=True),
    sa.Column('acceptance_criteria', sa.Text(), nullable=True),
    sa.Column('document_requires', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('requirement_id')
    )
    op.create_table('requirement_groups',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('original_requirement_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['original_requirement_id'], ['requirements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('requirement_workflows',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('requirement_id', sa.UUID(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('requirement_id')
    )
    op.create_table('requirement_dependences',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('source_requirement_id', sa.UUID(), nullable=False),
    sa.Column('target_requirement_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('strength', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('source_requirement_group_id', sa.UUID(), nullable=True),
    sa.Column('target_requirement_group_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['source_requirement_group_id'], ['requirement_groups.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_requirement_id'], ['requirements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_requirement_group_id'], ['requirement_groups.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_requirement_id'], ['requirements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('req_dependence_histories',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('prev_req_dependence_id', sa.UUID(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['prev_req_dependence_id'], ['requirement_dependences.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    # Вставка начальных данных
    insert_initial_data()


def insert_initial_data() -> None:
    """Вставка начальных данных: прав доступа и ролей"""

    # Используем connection для выполнения SQL запросов
    connection = op.get_bind()

    # Текущее время для всех записей
    now = datetime.utcnow()

    # Вставка прав доступа через прямые SQL запросы
    permissions_sql = sa.text("""
    INSERT INTO permissions (permission, description, created_at, updated_at) VALUES
    (:p1, :d1, :now, :now),
    (:p2, :d2, :now, :now),
    (:p3, :d3, :now, :now),
    (:p4, :d4, :now, :now),
    (:p5, :d5, :now, :now),
    (:p6, :d6, :now, :now),
    (:p7, :d7, :now, :now),
    (:p8, :d8, :now, :now),
    (:p9, :d9, :now, :now),
    (:p10, :d10, :now, :now);
    """)

    connection.execute(permissions_sql, {
        'p1': PermissionEnum.PROJECT_EDIT.value,
        'd1': 'Редактирование проекта',
        'p2': PermissionEnum.PROJECT_DELETE.value,
        'd2': 'Удаление проекта',
        'p3': PermissionEnum.PROJECT_MANAGE_USERS.value,
        'd3': 'Управление пользователями проекта',
        'p4': PermissionEnum.REQUIREMENT_CREATE.value,
        'd4': 'Создание требований',
        'p5': PermissionEnum.REQUIREMENT_READ.value,
        'd5': 'Чтение требований',
        'p6': PermissionEnum.REQUIREMENT_UPDATE.value,
        'd6': 'Обновление требований',
        'p7': PermissionEnum.REQUIREMENT_DELETE.value,
        'd7': 'Удаление требований',
        'p8': PermissionEnum.REQUIREMENT_APPROVE.value,
        'd8': 'Утверждение требований',
        'p9': PermissionEnum.REQUIREMENT_REJECT.value,
        'd9': 'Отклонение требований',
        'p10': PermissionEnum.REQUIREMENT_REVIEW.value,
        'd10': 'Проверка требований',
        'now': now
    })

    # Вставка ролей
    roles_sql = sa.text("""
    INSERT INTO roles (name, description, created_at, updated_at) VALUES
    (:n1, :desc1, :now, :now),
    (:n2, :desc2, :now, :now),
    (:n3, :desc3, :now, :now),
    (:n4, :desc4, :now, :now),
    (:n5, :desc5, :now, :now);
    """)

    connection.execute(roles_sql, {
        'n1': 'Владелец проекта',
        'desc1': 'Полный доступ ко всем функциям проекта',
        'n2': 'Менеджер проекта',
        'desc2': 'Управление проектом и участниками',
        'n3': 'Аналитик',
        'desc3': 'Работа с требованиями',
        'n4': 'Участник',
        'desc4': 'Базовый доступ к проекту',
        'n5': 'Рецензент',
        'desc5': 'Проверка и утверждение требований',
        'now': now
    })

    # Получаем ID прав доступа
    permission_ids = {}
    for perm in PermissionEnum:
        result = connection.execute(
            sa.text(
                "SELECT id FROM permissions WHERE permission = :permission"),
            {"permission": perm.value}
        )
        row = result.fetchone()
        if row:
            permission_ids[perm.value] = row[0]

    # Получаем ID ролей
    role_names = [
        'Владелец проекта',
        'Менеджер проекта',
        'Аналитик',
        'Участник',
        'Рецензент'
    ]

    role_ids = {}
    for role_name in role_names:
        result = connection.execute(
            sa.text("SELECT id FROM roles WHERE name = :name"),
            {"name": role_name}
        )
        row = result.fetchone()
        if row:
            role_ids[role_name] = row[0]

    # Подготавливаем данные для вставки связей ролей и прав
    role_permissions_data = []

    # Функция для добавления связи
    def add_role_permission(role_name, permission_value):
        if role_name in role_ids and permission_value in permission_ids:
            role_permissions_data.append({
                "role_id": role_ids[role_name],
                "permission_id": permission_ids[permission_value],
                "created_at": now,
                "updated_at": now
            })

    # Владелец проекта - все права
    add_role_permission("Владелец проекта",
                        PermissionEnum.PROJECT_EDIT.value)
    add_role_permission("Владелец проекта",
                        PermissionEnum.PROJECT_DELETE.value)
    add_role_permission("Владелец проекта",
                        PermissionEnum.PROJECT_MANAGE_USERS.value)
    add_role_permission("Владелец проекта",
                        PermissionEnum.REQUIREMENT_CREATE.value)
    add_role_permission("Владелец проекта",
                        PermissionEnum.REQUIREMENT_READ.value)
    add_role_permission("Владелец проекта",
                        PermissionEnum.REQUIREMENT_UPDATE.value)
    add_role_permission("Владелец проекта",
                        PermissionEnum.REQUIREMENT_DELETE.value)
    add_role_permission("Владелец проекта",
                        PermissionEnum.REQUIREMENT_APPROVE.value)
    add_role_permission("Владелец проекта",
                        PermissionEnum.REQUIREMENT_REJECT.value)
    add_role_permission("Владелец проекта",
                        PermissionEnum.REQUIREMENT_REVIEW.value)

    # Менеджер проекта - управление проектом и требованиями
    add_role_permission("Менеджер проекта",
                        PermissionEnum.PROJECT_EDIT.value)
    add_role_permission("Менеджер проекта",
                        PermissionEnum.PROJECT_MANAGE_USERS.value)
    add_role_permission("Менеджер проекта",
                        PermissionEnum.REQUIREMENT_CREATE.value)
    add_role_permission("Менеджер проекта",
                        PermissionEnum.REQUIREMENT_READ.value)
    add_role_permission("Менеджер проекта",
                        PermissionEnum.REQUIREMENT_UPDATE.value)
    add_role_permission("Менеджер проекта",
                        PermissionEnum.REQUIREMENT_DELETE.value)
    add_role_permission("Менеджер проекта",
                        PermissionEnum.REQUIREMENT_APPROVE.value)
    add_role_permission("Менеджер проекта",
                        PermissionEnum.REQUIREMENT_REJECT.value)
    add_role_permission("Менеджер проекта",
                        PermissionEnum.REQUIREMENT_REVIEW.value)

    # Аналитик - работа с требованиями
    add_role_permission("Аналитик",
                        PermissionEnum.REQUIREMENT_CREATE.value)
    add_role_permission("Аналитик", PermissionEnum.REQUIREMENT_READ.value)
    add_role_permission("Аналитик",
                        PermissionEnum.REQUIREMENT_UPDATE.value)
    add_role_permission("Аналитик",
                        PermissionEnum.REQUIREMENT_DELETE.value)
    add_role_permission("Аналитик",
                        PermissionEnum.REQUIREMENT_REVIEW.value)

    # Рецензент - проверка и утверждение
    add_role_permission("Рецензент", PermissionEnum.REQUIREMENT_READ.value)
    add_role_permission("Рецензент",
                        PermissionEnum.REQUIREMENT_APPROVE.value)
    add_role_permission("Рецензент",
                        PermissionEnum.REQUIREMENT_REJECT.value)
    add_role_permission("Рецензент",
                        PermissionEnum.REQUIREMENT_REVIEW.value)

    # Участник - базовый доступ
    add_role_permission("Участник", PermissionEnum.REQUIREMENT_READ.value)

    # Вставляем связи ролей и прав доступа
    if role_permissions_data:
        role_permissions_table = table(
            'role_permissions',
            column('id', sa.UUID()),
            column('role_id', sa.UUID()),
            column('permission_id', sa.UUID()),
            column('created_at', sa.DateTime),
            column('updated_at', sa.DateTime)
        )

        op.bulk_insert(role_permissions_table, role_permissions_data)



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('req_dependence_histories')
    op.drop_table('requirement_dependences')
    op.drop_table('requirement_workflows')
    op.drop_table('requirement_groups')
    op.drop_table('requirement_contents')
    op.drop_table('requirement_approvers')
    op.drop_table('req_workflow_histories')
    op.drop_table('req_content_histories')
    op.drop_index(op.f('ix_user_project_roles_user_id'), table_name='user_project_roles')
    op.drop_index(op.f('ix_user_project_roles_project_id'), table_name='user_project_roles')
    op.drop_table('user_project_roles')
    op.drop_table('requirements')
    op.drop_index(op.f('ix_role_permissions_role_id'), table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_table('projects')
    op.drop_index(op.f('ix_users_login'), table_name='users')
    op.drop_index(op.f('ix_users_external_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('permissions')
    # ### end Alembic commands ###
