"""api_key

Revision ID: 3176ed57f717
Revises: 1302e5c9144a
Create Date: 2026-01-16 19:24:55.646431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3176ed57f717'
down_revision: Union[str, Sequence[str], None] = '1302e5c9144a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integration_api_keys',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False, comment='Хэш API ключа'),
    sa.Column('key_prefix', sa.String(length=20), nullable=False, comment='Префикс ключа для идентификации (asut_int_xxxx)'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Название внешней системы'),
    sa.Column('description', sa.String(length=1000), nullable=True, comment='Описание назначения ключа'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Активен ли ключ'),
    sa.Column('expires_at', sa.DateTime(), nullable=True, comment='Срок действия ключа'),
    sa.Column('last_used_at', sa.DateTime(), nullable=True, comment='Последнее использование'),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_table('req_test_case_coverage',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('requirement_id', sa.UUID(), nullable=False),
    sa.Column('test_case_version_id', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('projects', sa.Column('code', sa.String(length=50), nullable=True, comment='Код проекта'))
    op.add_column('projects', sa.Column('test_system_id', sa.String(length=255), nullable=True, comment='ID проекта во внешней системе тестирования'))
    op.create_unique_constraint(None, 'projects', ['code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='unique')
    op.drop_column('projects', 'test_system_id')
    op.drop_column('projects', 'code')
    op.drop_table('req_test_case_coverage')
    op.drop_table('integration_api_keys')
    # ### end Alembic commands ###
